# MCU name
MCU = STM32F072

# Bootloader selection
BOOTLOADER = stm32-dfu
WS2812_DRIVER = spi
EXTRAKEY_ENABLE = yes
SLEEP_LED_ENABLE = no

COMBO_ENABLE = yes
ENCODER_MAP_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
OLED_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAFLAGS += -flto
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
SRC += oneshot.c

OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE